### ISSUE TITLE
Revelry - Time Tracking - Setup 10,000ft Project

### ISSUE THREAD

**Issue by Mcscott142** [big-neon/bn-mobile-react#23]
## Background
[10,000ft](https://app.10000ft.com/) is the time tracking and resourcing tool used at Revelry. If a project has not yet been setup, then @thomasknoll will need to create the project.

## Scenario: Look for Project in 10,000ft
Given I am a Reveler
- [ ] When I login to 10,000ft
- [ ] And view the [Projects](https://app.10000ft.com/projects) page
- [ ] Then I see the new project
- [ ] When I do not see the new project
- [ ] Then I assign Thomas to this ticket
- [ ] And Thomas adds the project to 10,000ft
