### ISSUE TITLE
Eject from Expo

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-mobile-react#52]
Eject the app from Expo
Create sub-issues and attach to this epic for all of the steps that will be required.
Let's document the process.
The obvious issues are going to be the scanning and push notifications that will need an overhaul.

**Comment by simple-taskic** [comment]
**Subtasks:**
**Done:**
- [x] - Eject expo dependency
- [x] - Create Android project structure
- [x] - Add Android project dependencies
- [x] - Create iOS project structure
- [x] - Add iOS project dependencies
- [x] - Update `package.json` dependencies

Opened
- [ ] - Setup analytics
- [ ] - https://github.com/segmentio/analytics-react-native#usage
- [ ] - Align iOS/Android version codes
- [ ] - Update Android applicationID and iOS bundleID
- [ ] - Do we want and how we want to continue to use [Sentry](https://github.com/getsentry/react-native-sentry)
- [ ] - Find a way to include release certificates
- [ ] - Find a way to send push notification token to Server
- [ ] - Expo's `Constants.installationId` ? not sure if we used good replacement => `DeviceInfo.getUniqueID()`
- [ ] - Recheck if we are sending good name for token source : await `server.users.deviceTokens.create({token, token_source: 'bnmobile'}) => "expo" replaced when "bnmobile"`
- [ ] - Facebook ID is missing - we need to find a way to import it privately
