### ISSUE TITLE
Developer - PR Template - Pull Request Checklist

### ISSUE THREAD

**Issue by Mcscott142** [big-neon/bn-mobile-react#7]
## Background
A Pull request template with a Checklist is a useful reminder of things to include when creating a Pull Request. Example template is below, feel free to edit based on your projects needs. Directions for adding a PR Template live [here](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/).

## Scenario: Pull Request Checklist
Given a repo has been set up
- [ ] When I open a pull request for the project
- [ ] Then I see a template for my PR similar to the example below

```
connect #[issue number]
#### Description: <!-- What changed? Why? -->

#### Reviewer don't-forgets:
- [ ] Test coverage feels appropriate, given potential risk
- [ ] We're not doubling down on already-bad code
- [ ] If there are web UI changes, they don't add anything that could be considered client-side page navigation (unless pre-approved as being necessary by another engineer)
- [ ] If there are web UI changes, they don't add any AJAX form submits (unless pre-approved as being necessary by another engineer)
- [ ] If there are any lint rules disabled, they are disabled per-line, and were (in the reviewer's judgment) appropriate to disable
- [ ] Any new environment variables used in the app are both documented and have been added to both staging and production environments already
- [ ] Potential race conditions are either inconsequential, or the code prevents them from occurring.
- [ ] If this is a UI change that called for screenshots/GIFs, in the reviewer's judgement, they were included
```
